DROP TABLE IF EXISTS public.roles CASCADE;
CREATE TABLE public.roles (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              created_at timestamp(6) NULL,
                              created_by varchar(255) NULL,
                              modified_at timestamp(6) NULL,
                              modified_by varchar(255) NULL,
                              role_name varchar(20) NULL,
                              CONSTRAINT roles_pkey PRIMARY KEY (id),
                              CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[]))),
	CONSTRAINT ukovpqau8r3lgfnmak7xyel2bt0 UNIQUE (role_name)
);

DROP TABLE IF EXISTS public.users CASCADE;
CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              created_at timestamp(6) NULL,
                              created_by varchar(255) NULL,
                              modified_at timestamp(6) NULL,
                              modified_by varchar(255) NULL,
                              account_expiry_date date NULL,
                              account_non_expired bool NOT NULL,
                              account_non_locked bool NOT NULL,
                              balance numeric(38, 2) NULL,
                              country_code varchar(2) NOT NULL,
                              credentials_expiry_date date NULL,
                              credentials_non_expired bool NOT NULL,
                              email varchar(50) NOT NULL,
                              enabled bool NOT NULL,
                              is_email_verified bool NOT NULL,
                              "password" varchar(120) NULL,
                              username varchar(20) NOT NULL,
                              role_id int8 NULL,
                              CONSTRAINT email UNIQUE (email),
                              CONSTRAINT username UNIQUE (username),
                              CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE public.users ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);

DROP TABLE IF EXISTS public.password_reset_token CASCADE;
CREATE TABLE public.password_reset_token (
                                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             created_at timestamp(6) NULL,
                                             created_by varchar(255) NULL,
                                             modified_at timestamp(6) NULL,
                                             modified_by varchar(255) NULL,
                                             expiry_date timestamptz(6) NOT NULL,
                                             "token" varchar(255) NOT NULL,
                                             used bool NOT NULL,
                                             user_id int8 NOT NULL,
                                             CONSTRAINT password_reset_token_pkey PRIMARY KEY (id),
                                             CONSTRAINT ukg0guo4k8krgpwuagos61oc06j UNIQUE (token)
);

ALTER TABLE public.password_reset_token ADD CONSTRAINT fk83nsrttkwkb6ym0anu051mtxn FOREIGN KEY (user_id) REFERENCES public.users(id);


DROP TABLE IF EXISTS public.email_verification_token CASCADE;
CREATE TABLE public.email_verification_token (
                                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                 created_at timestamp(6) NULL,
                                                 created_by varchar(255) NULL,
                                                 modified_at timestamp(6) NULL,
                                                 modified_by varchar(255) NULL,
                                                 expiry_date timestamptz(6) NOT NULL,
                                                 "token" varchar(255) NOT NULL,
                                                 used bool NOT NULL,
                                                 user_id int8 NOT NULL,
                                                 CONSTRAINT email_verification_token_pkey PRIMARY KEY (id),
                                                 CONSTRAINT ukidu2ippaks8bn6vcsq62khvdu UNIQUE (token)
);

ALTER TABLE public.email_verification_token ADD CONSTRAINT fkknax5in7pcatm2uf9uyple35x FOREIGN KEY (user_id) REFERENCES public.users(id);

DROP TABLE IF EXISTS public.package_plans CASCADE;
CREATE TABLE public.package_plans (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      created_at timestamp(6) NULL,
                                      created_by varchar(255) NULL,
                                      modified_at timestamp(6) NULL,
                                      modified_by varchar(255) NULL,
                                      country_code varchar(2) NOT NULL,
                                      credits int4 NOT NULL,
                                      expiry_date timestamp(6) NOT NULL,
                                      "name" varchar(255) NOT NULL,
                                      price numeric(38, 2) NOT NULL,
                                      CONSTRAINT package_plans_pkey PRIMARY KEY (id),
                                      CONSTRAINT pkg_name UNIQUE (name)
);

DROP TABLE IF EXISTS public.user_packages CASCADE;
CREATE TABLE public.user_packages (
                                      created_at timestamp(6) NULL,
                                      created_by varchar(255) NULL,
                                      modified_at timestamp(6) NULL,
                                      modified_by varchar(255) NULL,
                                      remaining_credits int4 NOT NULL,
                                      package_plan_id int8 NOT NULL,
                                      user_id int8 NOT NULL,
                                      CONSTRAINT user_packages_pkey PRIMARY KEY (package_plan_id, user_id)
);

ALTER TABLE public.user_packages ADD CONSTRAINT fk5qvjvutmu1iwl0wn0e2u2shf FOREIGN KEY (package_plan_id) REFERENCES public.package_plans(id);
ALTER TABLE public.user_packages ADD CONSTRAINT fklhj6dofmpikc4fp9nf3ciksdq FOREIGN KEY (user_id) REFERENCES public.users(id);

DROP TABLE IF EXISTS public.class_schedule CASCADE;
CREATE TABLE public.class_schedule (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       created_at timestamp(6) NULL,
                                       created_by varchar(255) NULL,
                                       modified_at timestamp(6) NULL,
                                       modified_by varchar(255) NULL,
                                       country_code varchar(2) NOT NULL,
                                       description varchar(255) NULL,
                                       end_time timestamp(6) NOT NULL,
                                       max_capacity int4 NOT NULL,
                                       "name" varchar(255) NOT NULL,
                                       required_credits int4 NOT NULL,
                                       start_time timestamp(6) NOT NULL,
                                       CONSTRAINT class_name UNIQUE (name),
                                       CONSTRAINT class_schedule_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.bookings CASCADE;
CREATE TABLE public.bookings (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 created_at timestamp(6) NULL,
                                 created_by varchar(255) NULL,
                                 modified_at timestamp(6) NULL,
                                 modified_by varchar(255) NULL,
                                 booked_at timestamp(6) NOT NULL,
                                 cancelled_at timestamp(6) NULL,
                                 checked_in bool NULL,
                                 credit_refunded bool NULL,
                                 class_id int8 NOT NULL,
                                 package_id int8 NOT NULL,
                                 user_id int8 NOT NULL,
                                 CONSTRAINT bookings_pkey PRIMARY KEY (id),
                                 CONSTRAINT uk6io6eavrlesc4v06ul7aop4br UNIQUE (user_id, class_id)
);

ALTER TABLE public.bookings ADD CONSTRAINT fkeyog2oic85xg7hsu2je2lx3s6 FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.bookings ADD CONSTRAINT fkf6wyx7850hf3icgoruk72dq3f FOREIGN KEY (package_id) REFERENCES public.package_plans(id);
ALTER TABLE public.bookings ADD CONSTRAINT fkh8h3fjrn2oq4hw519xa6w072d FOREIGN KEY (class_id) REFERENCES public.class_schedule(id);

DROP TABLE IF EXISTS public.waitlists CASCADE;
CREATE TABLE public.waitlists (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  created_at timestamp(6) NULL,
                                  created_by varchar(255) NULL,
                                  modified_at timestamp(6) NULL,
                                  modified_by varchar(255) NULL,
                                  pkg_id int8 NOT NULL,
                                  user_id int8 NOT NULL,
                                  class_id int8 NOT NULL,
                                  CONSTRAINT waitlists_pkey PRIMARY KEY (id)
);

ALTER TABLE public.waitlists ADD CONSTRAINT fk4kv92frn17srn83fmdvotoxfn FOREIGN KEY (class_id) REFERENCES public.class_schedule(id);
ALTER TABLE public.waitlists ADD CONSTRAINT fkapgrrvgbi28civjdxv78e7mea FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.waitlists ADD CONSTRAINT fkkya3qr2j07bt8yhvrrt3way6q FOREIGN KEY (pkg_id) REFERENCES public.package_plans(id);